CREATE TABLE IF NOT EXISTS attendees(
	id INT PRIMARY KEY,
	badge_name VARCHAR(100) NOT NULL,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	awarded TINYINT(1) NOT NULL DEFAULT 0
);
